apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-with-error
spec:
  steps:
  - name: step1-with-error
    onError: continue
    image: ubuntu
    command: 
      - /bin/bash
    args:
      - /bin/false 

  - name: step2
    image: ubuntu
    command:
      - bin/bash
    args:
      - echo "Step 2 - though there was en error in step1"
