apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: c1
      image: registry.redhat.io/ubi8/ubi-minimal 
      command:
        - /bin/bash
      args:
        - '-c' 
        - 'echo $(USERNAME) $(PASSWORD)'
      env:
       - name: USERNAME
         valueFrom:
           secretKeyRef:
             name: mysql-credentials
             key: username
       - name: PASSWORD
         valueFrom:
           secretKeyRef:
             name: mysql-credentials
             key: password 
  restartPolicy: Never
