apiVersion: v1
kind: Pod
metadata:
  name: pod-with-cm 
spec:
  containers:
  - name: c1
    image: registry.redhat.io/ubi8/ubi-minimal

    command:
    - /bin/bash
    args:        
    - -c
    - 'echo $(JDK_HOME) $(M2_HOME)'

    env:
    - name: JDK_HOME 
      valueFrom: 
        configMapKeyRef:
          name: tools-configmap
          key: JDK_PATH

    - name: M2_HOME 
      valueFrom:
        configMapKeyRef:
          name: tools-configmap
          key: M2_HOME

  restartPolicy: Never 
