apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv-jegan
  labels:
    name: jegan
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.1.80"
    path: "/mnt/nfs_share"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc-jegan
  labels:
    name: jegan
spec:
  selector:
    matchLabels:
      name: jegan
  resources:
    requests:
      storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: taskrun-with-pv-
spec:
  workspaces:
  - name: myworkspace
    persistentVolumeClaim:
      claimName: tekton-pvc-jegan
  taskSpec:
    steps:
    - name: task-with-pv
      image: ubuntu
      script: |
        echo $(workspaces.myworkspace.path) > $(workspaces.myworkspace.path)/path
    - name: print-path
      image: ubuntu
      script: cat $(workspaces.myworkspace.path)/path
    workspaces:
    - name: myworkspace
      mountPath: /my/myworkspace 
