apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: bitnami/wordpress:latest
        name: wordpress
        env:
          - name: WORDPRESS_DATABASE_USER
            value: root
          - name: WORDPRESS_DATABASE_PASSWORD 
            value: root@123
          - name: WORDPRESS_DATABASE_HOST
            value: mysql
          - name: WORDPRESS_DATABASE_PORT
            value: "3306"
          - name: WORDPRESS_DATABASE_NAME 
            value: bitnami_wordpress

          - name: MYSQL_CLIENT_FLAVOR
            value: mysql

          - name: MYSQL_CLIENT_DATABASE_HOST
            value: mysql
          - name: MYSQL_CLIENT_DATABASE_ROOT_USER
            value: root
          - name: MYSQL_CLIENT_DATABASE_ROOT_PASSWORD
            value: root@123
          - name: MYSQL_CLIENT_CREATE_DATABASE_NAME
            value: bitnami_wordpress
