apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: bitnami/mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
               name: mysql-credentials
               key: password
        volumeMounts:
        - name: mysql-storage
          mountPath: "/bitnami/mysql/data"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-jegan
