apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-jegan 
  labels:
    name: jegan
spec:
  capacity:
    storage: 250Mi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/mysql
    server: 192.168.1.80
