apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: bitnami/wordpress:latest
        name: wordpress
        env:
          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: username

          - name: WORDPRESS_DATABASE_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: password 

          - name: WORDPRESS_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress-cm
                key: database_host

          - name: WORDPRESS_DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: wordpress-cm
                key: database_port

          - name: WORDPRESS_DATABASE_NAME 
            valueFrom:
              configMapKeyRef:
                name: wordpress-cm
                key: database_name

          - name: MYSQL_CLIENT_FLAVOR
            valueFrom:
              configMapKeyRef:
                name: wordpress-cm
                key: database_client_flavor

          - name: MYSQL_CLIENT_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress-cm
                key: database_host

          - name: MYSQL_CLIENT_DATABASE_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: username

          - name: MYSQL_CLIENT_DATABASE_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: password

          - name: MYSQL_CLIENT_CREATE_DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: wordpress-cm
                key: database_name
